@startuml
autonumber
participant "EntryPoint" as ep
participant "Account" as account
participant "Paymaster" as pm
[->ep++ #gold: ""handleOps(userOps[])"":
group Validation
|||
ep->account++ #blue: <font color=blue> ""validateUserOp""
deactivate account
ep->pm++ #gray: ""validatePaymasterUserOp""
deactivate pm
ep->ep: deduct ""Paymaster"" deposit
|||
end
group Execution
|||
ep->account++ #blue: <font color=blue> ""executeUserOp""
    deactivate account
ep->pm++ #gray: ""postOp""
    deactivate pm
ep->ep: refund paymaster
|||
end
ep-->[: ""compensate(beneficiary)""
hide footbox
