on:
  workflow_run:
    workflows:
      - Continuous Integration
    types:
      - completed

# This is adapted from https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#workflow_run (2022-07-17)

name: Post Continuous Integration

permissions:
  pull-requests: write

jobs:
  ci:
    if: github.event.workflow_run.repository.owner.login == 'eips-wg'
    runs-on: ubuntu-latest
    steps:
      - name: Fetch PR Number
        uses: dawidd6/action-download-artifact@20319c5641d495c8a52e688b7dc5fada6c3a9fbc # v8
        with:
          name: pr_number
          workflow: ci.yml
          run_id: ${{ github.event.workflow_run.id }}

      - name: Save PR Data
        id: save-pr-data
        run: |
          echo "pr_number=$(cat pr_number)" >> $GITHUB_OUTPUT
          echo "pr_sha=$(cat pr_sha)" >> $GITHUB_OUTPUT
          echo "merge_sha=$(cat merge_sha)" >> $GITHUB_OUTPUT

      - name: Add Comment
        uses: marocchino/sticky-pull-request-comment@52423e01640425a022ef5fd42c6fb5f633a02728 # 2.9.1
        if: ${{ github.event.workflow_run.conclusion == 'failure' }}
        with:
          number: ${{ steps.save-pr-data.outputs.pr_number }}
          recreate: true
          message: |
            The commit ${{ steps.save-pr-data.outputs.pr_sha }} (as a parent of ${{ steps.save-pr-data.outputs.merge_sha }}) contains errors.
            Please inspect the [Run Summary](${{ github.event.workflow_run.html_url }}) for details.

      - name: Add Waiting Label
        uses: actions-ecosystem/action-add-labels@18f1af5e3544586314bbe15c0273249c770b2daf # 1.1.3
        if: ${{ github.event.workflow_run.conclusion == 'failure' }}
        with:
          labels: w-ci
          number: ${{ steps.save-pr-data.outputs.pr_number }}
          repo: ${{ github.repository }}
          github_token: ${{ github.token }}

      - name: Remove Waiting Label
        uses: actions-ecosystem/action-remove-labels@d05162525702062b6bdef750ed8594fc024b3ed7
        if: ${{ github.event.workflow_run.conclusion != 'failure' }}
        with:
          labels: w-ci
          number: ${{ steps.save-pr-data.outputs.pr_number }}
          repo: ${{ github.repository }}
          github_token: ${{ github.token }}


