on:
  workflow_run:
    workflows:
      - Continuous Integration
    types:
      - completed

name: Post Continuous Integration

jobs:
  ci:
    if: github.event.workflow_run.repository.owner.login == 'eips-wg'
    uses: eips-wg/build/.github/workflows/post-ci.yml@master
    secrets: inherit
    permissions:
      issues: write
      pull-requests: write
