name: Review Trigger

on:
  pull_request_target:
  pull_request_review:
  workflow_dispatch:
    inputs:
      pr_number:
        description: Pull Request Number
        type: string
        required: true
  issue_comment:
    types:
      - created

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  trigger:
    if: github.event.repository.owner.login == 'eips-wg'
    runs-on: ubuntu-latest
    name: Trigger Review
    steps:
      - name: Write PR Number - PR Target
        run: echo $PR_NUMBER > pr-number.txt
        env:
          PR_NUMBER: ${{ github.event.number }}
        if: |
          github.event_name == 'pull_request_target' &&
          !endsWith(github.event.sender.login, '-bot') &&
          !endsWith(github.event.sender.login, '[bot]')

      - name: Write PR Number - PR Review
        run: echo $PR_NUMBER > pr-number.txt
        env:
          PR_NUMBER: ${{ github.event.pull_request.number }}
        if: |
          github.event_name == 'pull_request_review' &&
          !endsWith(github.event.sender.login, '-bot') &&
          !endsWith(github.event.sender.login, '[bot]')

      - name: Write PR Number - Workflow Dispatch
        run: echo $PR_NUMBER > pr-number.txt
        if: github.event_name == 'workflow_dispatch'
        env:
          PR_NUMBER: ${{ inputs.pr_number }}

      - name: Write PR Number - Comment Retrigger
        run: echo $PR_NUMBER > pr-number.txt
        env:
          PR_NUMBER: ${{ github.event.issue.number }}
        if: |
          github.event_name == 'issue_comment' &&
          github.event.issue.pull_request &&
          contains(github.event.comment.body, '@eth-bot rerun')

      - name: Save PR Number
        uses: actions/upload-artifact@65c4c4a1ddee5b72f698fdd19549f0f0fb45cf08 # 4.6.0
        with:
          name: pr-number
          path: pr-number.txt
          if-no-files-found: ignore
