name: Review

on:
  workflow_run:
    workflows:
      - Review Trigger
    types:
      - completed

jobs:
  review:
    if: github.event.repository.owner.login == 'eips-wg'
    runs-on: ubuntu-latest
    name: Review
    steps:
      - name: Fetch PR Number
        uses: dawidd6/action-download-artifact@20319c5641d495c8a52e688b7dc5fada6c3a9fbc # v8
        with:
          name: pr-number
          workflow: review-trigger.yml
          run_id: ${{ github.event.workflow_run.id }}

      - name: Save PR Number
        id: save-pr-number
        run: echo "pr=$(cat pr-number.txt)" >> $GITHUB_OUTPUT

      - name: Auto Review Bot
        id: auto-review-bot
        uses: ethereum/eip-review-bot@eips-wg-dist
        continue-on-error: true
        with:
          token: ${{ secrets.TOKEN }}
          pr_number: ${{ steps.save-pr-number.outputs.pr }}
